### ISSUE TITLE
camelCase or Underscore

### ISSUE THREAD

**Issue by deepanshu88** [google/generative-ai-docs#105]
### Description of the bug:

Hi Team - I just wanted to highlight that fields in the request body are both in camelCase and Underscore in the  [REST API Guide](https://developers.generativeai.google/api/rest/generativelanguage/models/generateText) LINK . Check "candidate_count" in the first example and "Request body" section in the link. Wanted to confirm the right format.

**Comment by markmcd** [comment]
The API does support both styles, but I can see that being confusing too.

**Comment by markmcd** [comment]
I've updated the generation script & re-ran it. The examples in the REST API docs use `camelCase` now.

**Comment by markmcd** [comment]
e.g. https://developers.generativeai.google/api/rest/generativelanguage/models/generateText
