### ISSUE TITLE
max_output_tokens

### ISSUE THREAD

**Issue by deepanshu88** [google/generative-ai-docs#108]
what is the maximum value of this `max_output_tokens` argument? Can it take more than 10k tokens if I input some document in the prompt and expect output accordingly? I couldn't find `max_input_tokens` argument so assuming no limit for prompt..

**Comment by markmcd** [comment]
This is the PaLM documentation repository. For support you can head over to [the Discord](https://developers.generativeai.google/guide/discord).

The input and output context windows are documented [here](https://developers.generativeai.google/models/language), but `max_input_tokens` doesn't make sense as an argument - as the developer you have control over the input text.
