### ISSUE TITLE
Weird Response

### ISSUE THREAD

**Issue by deepanshu88** [google/generative-ai-docs#110]
When I use API for translation, it does not return output. Instead it applies some filtering like below..
```
{
  "filters": [
    {
      "reason": "OTHER"
    }
  ]
}
```

Here's my curl command. It works for "hindi" language but not for "german", that's weird.. But it works on Bard Website which I am assuming using the same API --
`$ curl https://generativelanguage.googleapis.com/v1beta2/models/text-bison-001:generateText?key=$PALM_API_KEY -H 'Content-Type: application/json' -X POST -d '{"prompt": { "text": "Act like a human translator and translate the following text to german language. \n I love you." } }'`

**Comment by suyogkute** [comment]
i also have the same issue. @markmcd can you direct us about this issue.
