### ISSUE TITLE
Convert Docs into markdown files

### ISSUE THREAD

**Issue by reynoldw** [google/generative-ai-docs#127]
### Description of the feature request:

For a normal business case, we have tons of docs, sheet, decks in the format of Google doc, Microsoft office, or PDF. I believe Doc Agent will be much more useful if it can convert those documents into markdown or directly into vector database. 

### What problem are you trying to solve with this feature?

I want to create assistive Agent to answer strategy, product and marketing answers instead of me. It can also be used by the junior team members to onboard and grow.

**Comment by nickvander** [comment]
Hi Rey,

I got some script to make this work (Google Docs, PDF, and emails (Gmail). I will do a little testing and cleanup and submit the scripts next week.

**Comment by nickvander** [comment]
Hey, I made a pull request that includes the request https://github.com/google/generative-ai-docs/pull/164

It should also get merged into the main repo soon.
