### ISSUE TITLE
Call for demo app maintainers

### ISSUE THREAD

**Issue by keertk** [google/generative-ai-docs#128]
Hi everyone,

We currently have [6 demo apps](https://github.com/google/generative-ai-docs/tree/main/demos/palm/web) hosted in this repository that are referenced in the [PaLM API site](https://developers.generativeai.google/develop/sample-apps). We're looking to folks in the community to help maintain them. This could include fixing issues, reviewing PR contributions, adding tests, making sure they're in a working state, etc.

- [list-it](https://github.com/google/generative-ai-docs/tree/main/demos/palm/web/list-it)
- [mood-food](https://github.com/google/generative-ai-docs/tree/main/demos/palm/web/mood-food)
- [quick-prompt](https://github.com/google/generative-ai-docs/tree/main/demos/palm/web/quick-prompt)
- [talking-character](https://github.com/google/generative-ai-docs/tree/main/demos/palm/web/talking-character)
- [textfx](https://github.com/google/generative-ai-docs/tree/main/demos/palm/web/textfx)
- [travel-planner](https://github.com/google/generative-ai-docs/tree/main/demos/palm/web/travel-planner)

If you're interested or have any questions, please reach out to us.
Thank you in advance for all your support and contributions!

cc @google/generative-ai-admin @google/gtech-llm-support

**Comment by tech-alpinist** [comment]
Hi
I am interested in these demo apps.
May I become a contributor? :)

**Comment by keertk** [comment]
Hi @tech-alpinist sorry for the delayed response! Yes, which demo would you like to maintain?

**Comment by tech-alpinist** [comment]
I would like to maintain the [talking-character](https://github.com/google/generative-ai-docs/tree/main/demos/palm/web/talking-character)

**Comment by keertk** [comment]
Fyi @markmcd

**Comment by tech-alpinist** [comment]
should I contact him?

**Comment by Ghat0tkach** [comment]
hey @keertk, even I'm very interested in managing, fixing issues, and becoming a contributor for mood-food or travel-planner🤩

**Comment by keertk** [comment]
Hi everyone, thank you for your patience as we worked through the new process after the launch. Please read through [this doc](https://github.com/google/generative-ai-docs/blob/main/DEMO_MAINTAINERS.md) and follow the instructions there if you're interested in maintaining a demo. Appreciate your contributions!
