### ISSUE TITLE
Does Palm support streaming ? 

### ISSUE THREAD

**Issue by ishaan-jaff** [google/generative-ai-docs#131]
### Description of the feature request:

I'm the maintainer of LiteLLM  https://github.com/BerriAI/litellm - we're trying to add an integration to Palm 

The docs do not mention support for streaming https://developers.generativeai.google/tutorials/chat_quickstart

do you support streaming ?

**Comment by keertk** [comment]
Thanks for opening this, @ishaan-jaff. We don't support streaming at the moment.
