### ISSUE TITLE
Working with PDF files

### ISSUE THREAD

**Issue by ImadSaddik** [google/generative-ai-docs#145]
### Description of the feature request:

Hello, I think adding the possibility to chat with PDF files will be a good feature to add.

**Comment by nickvander** [comment]
Hi, @ImadSaddik are you requesting this feature for the Docs Agent demo (demos/palm/python/docs-agent)?

**Comment by ImadSaddik** [comment]
Yes

**Comment by nickvander** [comment]
Great. I will add some scripts to support that early next week. I have some early scripts that allow us to work with Google Docs, PDFs, and emails (Gmail). I just need to some clean up and testing first.

**Comment by ImadSaddik** [comment]
Great, I am looking forward to trying it

**Comment by nickvander** [comment]
Hey, I made a pull request that includes the request https://github.com/google/generative-ai-docs/pull/164

It should also get merged into the main repo soon.

**Comment by ImadSaddik** [comment]
Great 😃

**Comment by nickvander** [comment]
The changes got merged in the main branch. 

I will enhance how PDFs get processed further down the road as right now it does a very "simple" conversion through OCR, but I will enhance this feature soon. In the meantime it should work with simple PDFs.

**Comment by ImadSaddik** [comment]
Thanks
