### ISSUE TITLE
International text FX

### ISSUE THREAD

**Issue by I-gio** [google/generative-ai-docs#180]
### Description of the feature request:

It would need to be able to use text FX tools in other languages than English.

### What problem are you trying to solve with this feature?

I would love to use these tools in my first language, Italian. And some other languages too, why not.

**Comment by keertk** [comment]
Hi there, the PaLM API only [supports English](https://developers.generativeai.google/available_regions#available_languages). Closing this as not planned and will revisit changes to TextFX in the future if needed.
