### ISSUE TITLE
AI Studio 403

### ISSUE THREAD

**Issue by RexRowan** [google/generative-ai-docs#192]
### Description of the bug:

![Screenshot - 14_12_2023 , 15_23_55](https://github.com/google/generative-ai-docs/assets/4164511/fbda0405-af1f-4b91-9110-de7dcf3c4dde)

**Comment by williamito** [comment]
Hi there; you typically get **Access restricted** if you're trying to use AI Studio outside an [available region](https://ai.google.dev/available_regions#available_regions). I'll close this for now, but please re-open and add details if that's not the case.
