### ISSUE TITLE
Query about sharing my fine-tuned model

### ISSUE THREAD

**Issue by hasan-sayeed** [google/generative-ai-docs#196]
Hi everyone,

I'm very new to this. I have a question. After I fine-tune a model through PaLM API on my own dataset how do I share my tuned model with others?

Thanks.

**Comment by markmcd** [comment]
There is a `PermissionService` in the API. It's not particularly well documented, but I started putting together a sample that shows how to share a tuned model over in #170. It's not approved or merged yet (my bad) but hopefully you can see the code.

**Comment by MarkDaoust** [comment]
Yes, no docs aside from the generated api-reference, and no support in the python SDK (`google.generativeai`), just the low-level client library (`google.ai.generativelanguage`).

Here's the entry point for the generated api-reference: https://ai.google.dev/api/python/google/ai/generativelanguage/PermissionServiceClient
