### ISSUE TITLE
Execute operation "model.generate_content(content).text" and cause error '*** IndexError: list index out of range'

### ISSUE THREAD

**Issue by UCC-team** [google/generative-ai-docs#197]
### Description of the bug:

model.generate_content(content).text

### Actual vs expected behavior:

(Pdb) len(content)
31256
(Pdb) model.generate_content(content)
<google.generativeai.types.generation_types.GenerateContentResponse object at 0x116f2b350>
(Pdb) rep = model.generate_content(content)
(Pdb) rep
<google.generativeai.types.generation_types.GenerateContentResponse object at 0x11758c350>
(Pdb) rep.text
*** IndexError: list index out of range

**Comment by MarkDaoust** [comment]
Hi, it would help to have a little more of the error detail, but this may be fixed in this commit: https://github.com/google/generative-ai-python/commit/0a9596f311f42aada40f8f11067411b4defe6e7f

Which was included in the 0.3.2 release.
