### ISSUE TITLE
SecretNotFoundError: Secret "GOOGLE_API_KEY" does not exist.

### ISSUE THREAD

**Issue by MattiaBaldinetti** [google/generative-ai-docs#207]
Hi!
I’m trying to run **python_quickstart** (https://github.com/google/generative-ai-docs/blob/main/site/en/tutorials/python_quickstart.ipynb)

But when I go to enter my key,  I get this error :  ```SecretNotFoundError: Secret My_Key does not exist.```
I tried to use another key,  but even with this I get this error

What could be the reason?

Have a nice day 🙂

**Comment by Ghat0tkach** [comment]
hey @MattiaBaldinetti , are you using google collab?

**Comment by MattiaBaldinetti** [comment]
Hi! @Ghat0tkach 
I’m trying both on Google Collab and in my local notebook, both give me this error

**Comment by Ghat0tkach** [comment]
> Hi! @Ghat0tkach 
> I’m trying both on Google Collab and in my local notebook, both give me this error

In google collab, we are supposed to create a variable for secret key , The variables should be accessible in the right sidebar (with the key 🗝️ icon)

**Comment by MattiaBaldinetti** [comment]
Hi! @Ghat0tkach 
Thanks, now it works!
Is there any way to run the code in my notebook locally?

**Comment by Ghat0tkach** [comment]
> Hi! @Ghat0tkach Thanks, now it works! Is there any way to run the code in my notebook locally?

Apologies for the late reply  , I havent tried to run it locally . probably we need to use export  Secret My_Key ="your key" some sort of thing . Im not sure about it🥲
