### ISSUE TITLE
Candidate was blocked due to SAFETY at the time when the BLOCK_NONE setting was set

### ISSUE THREAD

**Issue by kpripper** [google/generative-ai-docs#212]
### Description of the bug:

[GoogleGenerativeAI Error]: Candidate was blocked due to SAFETY

result.response.candidates[0].safetyRatings has the following value

```
 [
  { category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT', probability: 'LOW' },
  { category: 'HARM_CATEGORY_HATE_SPEECH', probability: 'NEGLIGIBLE' },
  { category: 'HARM_CATEGORY_HARASSMENT', probability: 'HIGH' },
  {
    category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
    probability: 'NEGLIGIBLE'
  }
]
```

My model.safetySettings

```
[
  { category: 'HARM_CATEGORY_HATE_SPEECH', threshold: 'BLOCK_NONE' },
  {
    category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
    threshold: 'BLOCK_NONE'
  },
  { category: 'HARM_CATEGORY_HARASSMENT', threshold: 'BLOCK_NONE' },
  {
    category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
    threshold: 'BLOCK_NONE'
  }
  ]
```

### Actual vs expected behavior:

Content should not be blocked.

**Comment by TTMOR** [comment]
Hello, @kpripper ! Well...even if you set it to 'BLOCK_NONE', you are still subject to the rules of the Google pretrained model, to which you don't have access. This model, which we don't have access to, governs the blocked categories in the pretrained model, following Google's rules and norms. I believe you can find these guidelines in the section where you look for your security settings and when you agree to use the API. I hope this helps! Regards! (:

**Comment by keertk** [comment]
@kpripper Could you share more information please? What was your input + API call?

**Comment by Chamidu0423** [comment]
Chamidu@Chamidu-PC:~/Documents/UI 2 WEB$ node app.js
Server is running on http://localhost:3000
Error processing image: GoogleGenerativeAIResponseError: [GoogleGenerativeAI Error]: Candidate was blocked due to RECITATION
    at response.text (/home/Chamidu/node_modules/@google/generative-ai/dist/index.js:256:23)
    at /home/Chamidu/Documents/UI 2 WEB/app.js:75:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  response: {
    candidates: [ [Object] ],
    promptFeedback: { safetyRatings: [Array] },
    text: [Function (anonymous)]
  }
}  
**### anyone Can help fix that???**

**Comment by HakimNB** [comment]
I have similar issue..

```
GoogleGenerativeAIResponseError: [GoogleGenerativeAI Error]: Candidate was blocked due to RECITATION
```

I am sending the prompt: "who are you"

**Comment by haiffy420** [comment]
my prompt is just what is 1 + 1, got the same error

**Comment by zakcali** [comment]
I got the same error with Gemini 1.5 Pro V1beta chat api.

`GoogleGenerativeAIResponseError: [GoogleGenerativeAI Error]: Text not available. Response was blocked due to OTHER`

my safety settings are `const safetySettings = [
  { 
    category: HarmCategory.HARM_CATEGORY_HARASSMENT, threshold: HarmBlockThreshold.BLOCK_NONE,
  },
    {
    category: HarmCategory.HARM_CATEGORY_HATE_SPEECH, threshold: HarmBlockThreshold.BLOCK_NONE,
  },
    {
    category: HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT, threshold: HarmBlockThreshold.BLOCK_NONE,
  },
    {
    category: HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT, threshold: HarmBlockThreshold.BLOCK_NONE,
  },
];`

my prompt is (in Turkish): 
`translate following to English: Opere meme Ca tanısıyla izlenen hastada sağ meme mastektomizedir. Mastektomi lojunda belirgin kitle lezyonu saptanmadı.`

I'm getting same error both in Google Aı Studio, and in my nodejs program using api

**Comment by alysonfarias** [comment]
i got the same error

**Comment by suelliton** [comment]
My language is portuguese, i send a prompt to gemini that says: "Gostaria de um resumo sobre a série pousando no amor", returns this error, 
Error: [GoogleGenerativeAI Error]: Candidate was blocked due to SAFETY at Object.response.functionCalls. But, if i send a prompt message saying: "Gostaria de um resumo sobre a série Crashing landing on you", returns the resume successfully, i dont understand...

**Comment by abooo96** [comment]
It would be good to know why this occurs. The same prompt works sometimes and sometimes not..

**Comment by abooo96** [comment]
Turns out you can circumvent this by giving better prompts. I had the issue for several days without any solution and bypassed it by giving a more detailed and 'less harmful' prompt but with the same content. The issue just vanished. :D

**Comment by logancyang** [comment]
I was considering gemini but this is making it almost unusable. Please do not block overly aggressively. The most simple prompts are blocked while it works for every other provider.
