### ISSUE TITLE
ReadTimeout: HTTPConnectionPool(host='localhost', port=36469): Read timed out. (read timeout=60.0)

### ISSUE THREAD

**Issue by G-TTYg** [google/generative-ai-docs#222]
### Description of the bug:

When I tried to use python code to call the gemin model on colab to generate a long article, it timed out. I couldn't find an option to extend the timeout.Is there any solution?

### Actual vs expected behavior:

response = model.generate_content(prompt_parts, stream=True)

---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py](https://localhost:8080/#) in _make_request(self, conn, method, url, body, headers, retries, timeout, chunked, response_conn, preload_content, decode_content, enforce_content_length)
    536         try:
--> 537             response = conn.getresponse()
    538         except (BaseSSLError, OSError) as e:

25 frames
TimeoutError: timed out

The above exception was the direct cause of the following exception:

ReadTimeoutError                          Traceback (most recent call last)
ReadTimeoutError: HTTPConnectionPool(host='localhost', port=36469): Read timed out. (read timeout=60.0)

During handling of the above exception, another exception occurred:

ReadTimeout                               Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/requests/adapters.py](https://localhost:8080/#) in send(self, request, stream, timeout, verify, cert, proxies)
    530                 raise SSLError(e, request=request)
    531             elif isinstance(e, ReadTimeoutError):
--> 532                 raise ReadTimeout(e, request=request)
    533             elif isinstance(e, _InvalidHeader):
    534                 raise InvalidHeader(e, request=request)

ReadTimeout: HTTPConnectionPool(host='localhost', port=36469): Read timed out. (read timeout=60.0)

**Comment by G-TTYg** [comment]
I solved the problem directly using the requests library.

**Comment by vishalnarnaware** [comment]
Hi @G-TTYg, Could you please share exactly what you did? I am facing the same issue.
Thanks
