### ISSUE TITLE
curl test get error code:429

### ISSUE THREAD

**Issue by John-zhan** [google/generative-ai-docs#236]
### Description of the bug:

excute the test below:
curl -H 'Content-Type: application/json' -d '{"contents":[{"parts":[{"text":"Write a story about a magic backpack"}]}]}' -X POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key={API key}
I get this code

{
  "error": {
    "code": 429,
    "message": "Resource has been exhausted (e.g. check quota).",
    "status": "RESOURCE_EXHAUSTED"
  }
}

**Comment by keertk** [comment]
Hi there! Could you try again please? There seems to have been a resource issue earlier but should be fine now. Feel free to reopen if needed.

**Comment by senzyo** [comment]
I encountered a strange situation. 
When I use the `v1beta` version, there is no problem; however, when using the `v1` version, an error occurs with error code 429: 
```
{
  "error": {
    "code": 429,
    "message": "Quota exceeded for quota metric 'Generate Content API requests per minute' and limit 'GenerateContent request limit per minute for a region' of service 'generativelanguage.googleapis.com' for consumer 'project_number:696498078762'.",
    "status": "RESOURCE_EXHAUSTED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "RATE_LIMIT_EXCEEDED",
        "domain": "googleapis.com",
        "metadata": {
          "quota_limit": "GenerateContentRequestsPerMinutePerProjectPerRegion",
          "consumer": "projects/696498078762",
          "quota_limit_value": "0",
          "service": "generativelanguage.googleapis.com",
          "quota_location": "us-west4",
          "quota_metric": "generativelanguage.googleapis.com/generate_content_requests"
        }
      },
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Request a higher quota limit.",
            "url": "https://cloud.google.com/docs/quota#requesting_higher_quota"
          }
        ]
      }
    ]
  }
}
```
I checked the [Quotas & System Limits for project "Generative Language Client"](https://console.cloud.google.com/iam-admin/quotas) page and found that my usage did not exceed the quota limit.  In fact, the usage percentage in every region is 0%. 
I don't know what's wrong with my account.

**Comment by senzyo** [comment]
To help others facing the same issue as me, I'm documenting my solution: 
I tried regenerating the API KEY and even deleting it before creating a new one, but the issue persisted. 
In the end, frustrated, I **deleted** the `Generative Language Client` project and then **recreated** it. 
Afterward, I generated a new API KEY. Finally, the problem disappeared.

**Comment by luoxufeiyan** [comment]
Same issue here.

After a diligent search effort, I have found that the issue is that Google detects my project violates the ToS. 

Go to https://console.cloud.google.com/cloud-resource-manager and check whether any project is warned.
