### ISSUE TITLE
MediaPipe folder misplaced

### ISSUE THREAD

**Issue by 200210qb** [google/generative-ai-docs#24]
it's in the third-party directory. when running, the mediapipe_audio_blendshape reports module not found. Simple mitigation by copying the mediapipe folder over inside /src

<img width="333" alt="image" src="https://github.com/google/generative-ai-docs/assets/61844929/18a479df-35a1-4b98-99e1-d50edfc78c7b">

**Comment by JacobGoldenArt** [comment]
I think that's by design. but I'm not sure why. If you look in the the package.json. the start script, copies those files into src.   "scripts": {
    "start": "cp -r third_party/mediapipe/ ./src/apis/ & react-scripts start",

**Comment by 200210qb** [comment]
ah you are right... not sure why the copy didn't actually succeed in my case. anyways. thanks!

**Comment by shuaibaslam2019** [comment]
I am trying to run the project on a Windows environment but the copy didn't succeed then I did the following 

"scripts": {
    "start": "xcopy /E /I third_party\\mediapipe\\ src\\apis\\ && set NODE_ENV=development && start react-scripts start",
    
    

Now, I am facing the following error 

Module not found: Can't resolve './mediapipe/web/graph_runner/graph_runner' in 'C:\generative-ai-docs\demos\palm\web\talking-character\src\apis'

@JacobGoldenArt Could you please help to figure it out.

Thanks!
