### ISSUE TITLE
google.api_core.exceptions.PermissionDenied: 403

### ISSUE THREAD

**Issue by zzj0402** [google/generative-ai-docs#317]
### Description of the bug:

Trying to use AI Studio locally with the Gemini tuned model with the following code:

```
"""
At the command line, only need to run once to install the package via pip:

$ pip install google-generativeai
"""

import google.generativeai as genai

genai.configure(api_key="YOUR_API_KEY")

# Set up the model
generation_config = {
  "temperature": 0.9,
  "top_p": 1,
  "top_k": 1,
  "max_output_tokens": 8192,
}

safety_settings = [
  {
    "category": "HARM_CATEGORY_HARASSMENT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_HATE_SPEECH",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
]

model = genai.GenerativeModel(model_name="tunedModels/sdfs-dfsf-sdfsadf",
                              generation_config=generation_config,
                              safety_settings=safety_settings)

prompt_parts = [
  BLABLABLA
]

response = model.generate_content(prompt_parts)
print(response.text)
```

### Actual vs expected behavior:

Expect return a generated response but get:
```
envs\gemini\lib\site-packages\google\api_core\grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.PermissionDenied: 403 You do not have permission to access tuned model tunedModels/sdfsdfasdfasdfa.
```

**Comment by rawsid11** [comment]
same error

**Comment by singhniraj08** [comment]
@zzj0402, This repository is for issues related to website(https://ai.google.dev/) like documentation bugs or improvements. For issues related to AI Studio, we would suggest you to use "Send Feedback" option in AI Studio. Ref: Screenshot below. Thank you!

![image](https://github.com/google/generative-ai-docs/assets/110809167/21aa6fb5-1501-49ba-a9c7-2fccbef56542)

**Comment by kohry** [comment]
Same error here. 
I assume oauth is somewhat related to this issue, and I think people need some additional guidance.
https://ai.google.dev/docs/oauth_quickstart

**Comment by harinaralasetty** [comment]
This issue is still there, the code given in ai studio doesn't work with the ai studio api key. 

Error: 
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.PermissionDenied: 403 You do not have permission to access tuned model tunedModels/nextnum-k7f103e3mv0y.

**Comment by SUBASHPALVEL** [comment]
Same error. Not able to access the fine tuned model.

**Comment by palak-aartas** [comment]
gcloud auth application-default login --client-id-file client_secret.json --scopes='https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/generative-language.tuning'
Try this command, first get a client_secret: https://ai.google.dev/gemini-api/docs/oauth
But i am stuck in a weird situation. This method works when i run a standalone python script but it doesnt work when i add the gemini model in a django api.

**Comment by palak2665** [comment]
gcloud auth application-default login --client-id-file client_secret.json --scopes='https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/generative-language.tuning'
Try this command, first get a client_secret: https://ai.google.dev/gemini-api/docs/oauth
But i am stuck in a weird situation. This method works when i run a standalone python script but it doesnt work when i add the gemini model in a django api.
