### ISSUE TITLE
An internal error when uploading files

### ISSUE THREAD

**Issue by paleboat** [google/generative-ai-docs#329]
I uploaded a folder this morning and got the following error and could not run it. Please review the attachment. 
![Screenshot 2024-03-25 110714](https://github.com/google/generative-ai-docs/assets/3837611/ff85a64a-12ad-466c-971e-a198f8c83ac3)

**Comment by ymodak** [comment]
Hi @paleboat Thanks for your issue. This looks like an intermittent error and should work now. Also for future reports related to AI Studio please use send feedback button.
![image](https://github.com/google/generative-ai-docs/assets/42785357/8adfc526-c8af-4063-9548-84711af61227)
