### ISSUE TITLE
Language model API key

### ISSUE THREAD

**Issue by 200210qb** [google/generative-ai-docs#33]
I wonder what's the [LANGUAGE_MODEL_API_KEY needed here](https://github.com/google/generative-ai-docs/blob/main/demos/palm/web/talking-character/src/context/constants.ts#L19)? Is it the same API KEY as GOOGLE_CLOUD_API_KEY that I get from google cloud console? If not, I struggle to find how to generate a separate language model api key despite I have Vertex AI enabled. 

Could someone please help? Thanks!

<img width="644" alt="image" src="https://github.com/google/generative-ai-docs/assets/61844929/79b341a8-6612-42ba-93ae-08d6060f22b0">

**Comment by MarkDaoust** [comment]
> I wonder what's the LANGUAGE_MODEL_API_KEY needed here

It looks like it that example they have it setup to optionally use different API keys for the PaLM API and the other cloud services. If you search in this repo you'll see that the language model key is used for the generateMessage URL (this API), and the [Google cloud API key is used for the speech <-> text](https://github.com/search?q=repo%3Agoogle%2Fgenerative-ai-docs%20google_cloud_api_key&type=code)

> Is it the same API KEY as GOOGLE_CLOUD_API_KEY that I get from google cloud console? 

I think you could use the same key for both, if all the necessary APIs are enabled on the project  (APIs & Services > Enabled APIs ).

> Vertex AI enabled.

This is unrelated to vertex.

**Comment by 200210qb** [comment]
I tried to use the same API key for both, but then failed on the language model api call. Apparently it requires a separate API key per their site: 

"[Join the waitlist](https://makersuite.google.com/waitlist) to get your API key via MakerSuite and start prototyping quickly"

**Comment by MarkDaoust** [comment]
Yeah, I could have been clearer. 

> You need to have both api enabled in your project.

To enable the API you need to get through the waitlist, you should get through it pretty quickly. 
Once you're through the waitlist the API should appear in the list of APIs you can enable.

**Comment by 200210qb** [comment]
Perfect. Thanks a lot for clarifying, Mark!
