### ISSUE TITLE
Possiblitie to further tune a tuned model

### ISSUE THREAD

**Issue by wired87** [google/generative-ai-docs#339]
### Description of the feature request:

Currently its just "allowed" to tune a model once. That restricts the handling enormously. It were be way better with the possibilitie to tune the model multiple times (when new data are available). 

### What problem are you trying to solve with this feature?

To extend the usecase of Gemini

### Any other information you'd like to share?

Is something like that planed?

**Comment by singhniraj08** [comment]
@wired87, Thank you reporting this issue. This repository is for issues related to website(https://ai.google.dev/) like documentation bugs or improvements. For issues related to Gemini, we would suggest you to use "Send Feedback" option in Gemini docs. Ref: Screenshot below.

![image](https://github.com/google/generative-ai-docs/assets/110809167/7d11fa96-c1dc-45eb-bb7c-ec8d6609c383)
