### ISSUE TITLE
Gemini Pro 1.0 returns 500 errors when sending back its own responses during multiturn conversations

### ISSUE THREAD

**Issue by ryao** [google/generative-ai-docs#348]
### Description of the bug:

Sometimes, Gemini pro 1.0 will emit `<ctrl100></ctrl100>` in its output. If you send that back, you will get a 500 error. I have also seen it emit `<ctrl99></ctrl99>` too, but I have not experimented to see if that also causes a problem. The one time I ever saw it also had `<ctrl100></ctrl100>` in the output.

### Actual vs expected behavior:

It should return a response, not generate a 500 error.

### Any other information you'd like to share?

Here is a test case that expects API_KEY to defined in the environment. It demonstrates this issue:

```
#!/usr/bin/env bash

export MODEL="gemini-1.0-pro-latest"

curl \
  -X POST https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent?key=${API_KEY} \
  -H 'Content-Type: application/json' \
  -d @<(echo '{
  "contents": [
        {"role":"user",
         "parts":[{
           "text": "Write the first line of a story about a magic backpack."}]},
        {"role": "model",
         "parts":[{
           "text": "In the bustling city of Meadow brook, lived a young girl named Sophie. She was a bright and curious soul with an imaginative mind.<ctrl100></ctrl100>"}]},
        {"role": "user",
         "parts":[{
           "text": "Can you set it in a quiet village in 1600s France?"}]},
      ],
  "generationConfig": {
    "temperature": 0.9,
    "topK": 1,
    "topP": 1,
    "maxOutputTokens": 2048,
    "stopSequences": []
  },
  "safetySettings": [
    {
      "category": "HARM_CATEGORY_HARASSMENT",
      "threshold": "BLOCK_NONE"
    },
    {
      "category": "HARM_CATEGORY_HATE_SPEECH",
      "threshold": "BLOCK_NONE"
    },
    {
      "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
      "threshold": "BLOCK_NONE"
    },
    {
      "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
      "threshold": "BLOCK_NONE"
    }
  ]
}')
```

Here is the output:

```
$ bash test.sh 
{
  "error": {
    "code": 500,
    "message": "An internal error has occurred. Please retry or report in https://developers.generativeai.google/guide/troubleshooting",
    "status": "INTERNAL"
  }
}
```

Also, I believe this issue was reported here:

https://github.com/google/generative-ai-python/issues/179

Unfortunately, when using the latest code, the 500 error is not reported and you get a backtrace that suggests there is a local problem, rather than one that tells of a 500 error.

**Comment by singhniraj08** [comment]
@ryao, This looks like an intermittent error and should work now. 
This repository is for issues related to website(https://ai.google.dev/) like documentation bugs or improvements. For issues related to Gemini API, we would suggest you to use "Send Feedback" option in Gemini docs. Ref: Screenshot below.

![image](https://github.com/google/generative-ai-docs/assets/110809167/7d11fa96-c1dc-45eb-bb7c-ec8d6609c383)

**Comment by ryao** [comment]
> @ryao, This looks like an intermittent error and should work now. This repository is for issues related to website(https://ai.google.dev/) like documentation bugs or improvements. For issues related to Gemini API, we would suggest you to use "Send Feedback" option in Gemini docs. Ref: Screenshot below.

It had been unclear where to file the report since there was no option listed for reporting issues in the infrastructure. Upon asking others in discord, I settled on filing here. I just sent feedback with a link to this issue.
