### ISSUE TITLE
Copy to Clipboard Google AI Studio

### ISSUE THREAD

**Issue by fredroo** [google/generative-ai-docs#353]
### Description of the bug:

When I try copy results of my prompts to Google Docs, 

### Actual vs expected behavior:

Example a word STAR return only S inside the full TEXT

### Any other information you'd like to share?

in this case, my text input and output is pt-BR (Portuguese Brazil)

**Comment by singhniraj08** [comment]
@fredroo, Thank you reporting this issue. This repository is for issues related to website(https://ai.google.dev/) like documentation bugs or improvements. For issues related to AI Studio, we would suggest you to use "Send Feedback" option in AI Studio. Ref: Screenshot below. Thank you!

![image](https://github.com/google/generative-ai-docs/assets/110809167/21aa6fb5-1501-49ba-a9c7-2fccbef56542)
