### ISSUE TITLE
finishReason:OTHER

### ISSUE THREAD

**Issue by jesulo** [google/generative-ai-docs#354]
### Description of the bug:

I have response finishReason:OTHER all time when make curl to api gemini generative. What does that error refer to, there isn't much detail, regards

**Comment by jesulo** [comment]
now ... {
  "errorMessage": "The service was not able to process your request",
  "errorDetails": {
    "rawErrorMessage": [
      "500 - \"{\\n  \\\"error\\\": {\\n    \\\"code\\\": 500,\\n    \\\"message\\\": \\\"An internal error has occurred. Please retry or report in https://developers.generativeai.google/guide/troubleshooting\\\",\\n    \\\"status\\\": \\\"INTERNAL\\\"\\n  }\\n}\\n\""
    ],
    "httpCode": "500"
  },
  "n8nDetails": {
    "nodeName": "Texto existe",
    "nodeType": "n8n-nodes-base.httpRequest",
    "nodeVersion": 4.1,
    "itemIndex": 0,
    "time": "6/4/2024, 17:51:46",
    "n8nVersion": "1.33.1 (Self Hosted)",
    "binaryDataMode": "default"

**Comment by singhniraj08** [comment]
@jesulo, Thank you reporting this issue. This looks like an intermittent error and should work now. 
This repository is for issues related to website(https://ai.google.dev/) like documentation bugs or improvements. For issues related to Gemini, we would suggest you to use "Send Feedback" option in Gemini docs. Ref: Screenshot below.

![image](https://github.com/google/generative-ai-docs/assets/110809167/7d11fa96-c1dc-45eb-bb7c-ec8d6609c383)
