### ISSUE TITLE
About video input

### ISSUE THREAD

**Issue by gemcollector** [google/generative-ai-docs#361]
### Description of the feature request:

Fantastic work! I wonder if is it possible to input a video (.mp4) while using gemini-1.5-pro api? The tutorial seems to only provide access to a single image. 

### What problem are you trying to solve with this feature?

I wanna input a video sequence, just like the web version.

**Comment by singhniraj08** [comment]
@gemcollector, [Video formats](https://ai.google.dev/gemini-api/docs/prompting_with_media#video_formats) are supported for Gemini 1.5 pro api. For larger images, videos (sequences of image frames), and audio, upload the files with the [File API](https://ai.google.dev/api/rest/v1beta/files) before including them in prompts. Thank you!

**Comment by gemcollector** [comment]
Thanks for your reply~! So Does it mean if we wanna upload the videos, we can only upload sequences of image frames instead of directly uploading the `.mp4` file？

**Comment by gemcollector** [comment]
I have seen the instructions, thank you !

**Comment by gemcollector** [comment]
Are there any examples I can refer to? Thank you!

**Comment by gemcollector** [comment]
I think this repo can solve my question! Thanks! https://github.com/google-gemini/cookbook

**Comment by singhniraj08** [comment]
@gemcollector, Sorry for delayed response. You can follow [Gemini API: Prompting with Video](https://github.com/google-gemini/cookbook/blob/main/quickstarts/Video.ipynb) tutorial. The Gemini API currently does not support video files directly. Instead, you can provide a series of timestamps and image files. Thank you!
