### ISSUE TITLE
google.colab can‘t be installed

### ISSUE THREAD

**Issue by SheldonLiu0412** [google/generative-ai-docs#364]
### Description of the bug:

google.colab can‘t be pip installed,The reason is that the wheel cannot be executed for pandas.I have tried many methods but can't solve it. Is there any alternative solution

**Comment by singhniraj08** [comment]
@SheldonLiu0412, [google-colab](https://pypi.org/project/google-colab/) is a Colaboratory specific python library. For issues related to colab, please file a bug in [colabtools](https://github.com/googlecolab/colabtools/issues). This repository is for issues related to website(https://ai.google.dev/) like documentation bugs or improvements. Thank you!

**Comment by MarkDaoust** [comment]
Hi, you don't need anything in `google.colab` if you're running locally. 

Instead of `userdata.get('GOOGLE_API_KEY')`  just set the API key in a `GOOGLE_API_KEY` environment variable. and the python SDK will pick it up automatically, you don't even need the `genai.configure(api_key=` line.

**Comment by SheldonLiu0412** [comment]
> Hi, you don't need anything in `google.colab` if you're running locally.
> 
> Instead of `userdata.get('GOOGLE_API_KEY')` just set the API key in a `GOOGLE_API_KEY` environment variable. and the python SDK will pick it up automatically, you don't even need the `genai.configure(api_key=` line.
Thanks, it can solve the problem.
I try to use 'conda install -c conda-forge google-colab' , it works too
