### ISSUE TITLE
503 failed to connect to all addresses

### ISSUE THREAD

**Issue by SheldonLiu0412** [google/generative-ai-docs#367]
### Description of the bug:

langchain_google_genai._common.GoogleGenerativeAIError: Error embedding content: Timeout of 60.0s exceeded, last exception: 503 failed to connect to all addresses; last error: UNKNOWN: ipv4:142.251.43.10:443: tcp handshaker shutdown

### Actual vs expected behavior:

langchain work with pinecone-document

**Comment by chengwen0926** [comment]
add the following code to your code
'''
import os

os.environ["http_proxy"] = "http://127.0.0.1:7890"
os.environ["https_proxy"] = "http://127.0.0.1:7890"
'''
