### ISSUE TITLE
Missing notebook linked in tuning quickstart

### ISSUE THREAD

**Issue by xinyij-goo** [google/generative-ai-docs#371]
### Description of the bug:

https://github.com/google/generative-ai-docs/blob/main/site/en/tutorials/tuning_quickstart_python.ipynb

Link mentioned in "Before you can run this tutorial, you'll need to [setup OAuth for your project](https://colab.sandbox.google.com/github/google/generative-ai-docs/blob/main/site/en/tutorials/oauth_quickstart.ipynb)." leads to nowhere

### Actual vs expected behavior:

Link leads to an actual notebook / doc

**Comment by singhniraj08** [comment]
@xinyij-goo, Please follow [Gemini API: OAuth Quickstart](https://github.com/googlegemini/cookbook/blob/main/quickstarts/Authentication_with_OAuth.ipynb) tutorial. I have created and linked a PR to update the broken links. Thank you!
