### ISSUE TITLE
Persian language Support for Gemini API

### ISSUE THREAD

**Issue by Sinazrp** [google/generative-ai-docs#407]
### Description of the feature request:

 gemini  support persian language in public use but does not support it in API  this cause limitation for making worldwide app i hope you add persian support to gemini API

### What problem are you trying to solve with this feature?

make worldwide apps

**Comment by op30mmd** [comment]
Yes, good request

**Comment by mehrab-heidary** [comment]
Yes, please consider this request

**Comment by mahdinazmi** [comment]
Great request. please consider.

**Comment by mahdi-ghassemi** [comment]
Yes. Please consider.

**Comment by Amohasan23** [comment]
Please add persian language api

**Comment by mohammadJavad12** [comment]
**Yes. please consider I need this.**

**Comment by singhniraj08** [comment]
@Sinazrp, Thank you reporting this issue. 
This repository is for issues related to website(https://ai.google.dev/) like documentation bugs or improvements. For issues related to Gemini API, we would suggest you to use "Send Feedback" option in [Gemini docs](https://ai.google.dev/gemini-api/docs/api-key). Ref: Screenshot below.

![image](https://github.com/google/generative-ai-docs/assets/110809167/7d11fa96-c1dc-45eb-bb7c-ec8d6609c383)

**Comment by Amirioelmos** [comment]
Yes, please consider this request

**Comment by op30mmd** [comment]
Its now working![Screenshot_20240821_214010_Brave.jpg](https://github.com/user-attachments/assets/42d2fb39-08a2-4631-afd0-1d1f44e646b3)

**Comment by Sinazrp** [comment]
> Its now working![Screenshot_20240821_214010_Brave.jpg](https://github.com/user-attachments/assets/42d2fb39-08a2-4631-afd0-1d1f44e646b3)
> 
> 

It's not API,

**Comment by op30mmd** [comment]
> > Its now working![Screenshot_20240821_214010_Brave.jpg](https://github.com/user-attachments/assets/42d2fb39-08a2-4631-afd0-1d1f44e646b3)
> > 
> > 
> 
> It's not API, 

It is, i tested with api

**Comment by amirism** [comment]
Gemini speech generation is live in AI Studio, and you can type a prompt in Persian and hear the synthesized speech. Get ready to be amazed!!
