### ISSUE TITLE
How to save fine tuned PaliGemma model?

### ISSUE THREAD

**Issue by SkalskiP** [google/generative-ai-docs#424]
### Description of the feature request:

Hi 👋🏻 

Thanks a lot for PaliGemma fine-tune example [notebook](https://github.com/google/generative-ai-docs/blob/main/site/en/gemma/docs/paligemma/fine-tuning-paligemma.ipynb). It worked without any issue. However, it lacks the last step - saving a fine-tuned model. (Or I'm just missing something.) I'd appreciate any help. Thank you. 🙏🏻

**Comment by gokayfem** [comment]
+1 We need this

**Comment by selamw1** [comment]
Hi @SkalskiP,

Based on this conversation at [X](https://twitter.com/__kolesnikov__/status/1791073793403727981), you can use [numpy.savez](https://numpy.org/doc/stable/reference/generated/numpy.savez.html#numpy.savez), a function that efficiently stores multiple arrays in a single, uncompressed `.npz` format.

```Python
import big_vision.utils as bv_utils
flat, _ = bv_utils.tree_flatten_with_names(flat)
with open("ckpt.npz", "wb") as f:
  np.savez(f, **{k: v for k, v in flat})
```

And then load:

```Python
bv_utils.load_checkpoint_np("ckpt.npz")
```

**Comment by milaomrani** [comment]
what is flat? what should I replace here? 
flat, _ = bv_utils.tree_flatten_with_names(flat)
