### ISSUE TITLE
429 StatusCode "Resource has been exhausted" , Check Quota

### ISSUE THREAD

**Issue by saramirabi** [google/generative-ai-docs#438]
### Description of the bug:

Hello Dears, 
I implement a question generator agent with Gemini (model= gemini-pro) and it was working properly till last week and from then I am receiving this confusing error, What should I do? Any suggestion?
**ERROR**: 
429 Resource has been exhausted (e.g. check quota).
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.RESOURCE_EXHAUSTED
	details = "Resource has been exhausted (e.g. check quota)."
	debug_error_string = "UNKNOWN:Error received from peer ipv4: ########:443 {created_time:"2024-05-26T04:18:56.862289+00:00", grpc_status:8, grpc_message:"Resource has been exhausted (e.g. check quota)."}"

 Here is the Code: 
```
import google.generativeai as genai
from dotenv import load_dotenv
import os
from datetime import datetime
import re
import time

def main():
    load_dotenv()
    os.environ['GOOGLE_API_KEY'] = "API_KEY"
    if not os.environ['GOOGLE_API_KEY']:
        raise ValueError(
            "API key not found. Please set your GEMINI_API_KEY in the environment.")

    genai.configure(api_key=os.environ['GOOGLE_API_KEY'])

    generation_config = {
        "temperature": 0.7,
        "top_p": 1,
        "top_k": 1,
        "max_output_tokens": 150,
    }

    safety_settings = {
        "HARM_CATEGORY_HARASSMENT": "BLOCK_NONE",
        "HARM_CATEGORY_HATE_SPEECH": "BLOCK_NONE",
        "HARM_CATEGORY_SEXUALLY_EXPLICIT": "BLOCK_NONE",
        "HARM_CATEGORY_DANGEROUS_CONTENT": "BLOCK_NONE",
    }


    model = genai.GenerativeModel(
        'gemini-1.5-pro-latest', generation_config=generation_config, safety_settings=safety_settings)
    chat = model.start_chat(history=[])

    while True:
        generate_prompt_qg = [f"""
        Ask a question about weather                                                        
        """]
        print("#################################")
        time.sleep(5)
        question = chat.send_message(generate_prompt_qg)
        user_input = question.text.strip()
        print(user_input)


if __name__ == "__main__":
    main()
```

Please be informed that I recreate another project with new API key but the problem still exists. 
This is the status of my errors: 
![image](https://github.com/google/generative-ai-docs/assets/6408254/ff6d9bcf-3d60-4d03-b5f9-1f54f3ec4edd)
and this is the status of my traffic:
![image](https://github.com/google/generative-ai-docs/assets/6408254/f996c969-e1a5-4c1c-9265-a790c4e35016)

```
The Limitation Quota: {
  "displayName": "",
  "userLabels": {},
  "conditions": [
    {
      "displayName": "Consumed API - Request count",
      "conditionThreshold": {
        "filter": "resource.type = \"consumed_api\" AND metric.type = \"serviceruntime.googleapis.com/api/request_count\"",
        "aggregations": [
          {
            "alignmentPeriod": "300s",
            "crossSeriesReducer": "REDUCE_NONE",
            "perSeriesAligner": "ALIGN_RATE"
          }
        ],
        "comparison": "COMPARISON_GT",
        "duration": "0s",
        "trigger": {
          "count": 1
        }
      }
    },
    {
      "displayName": "Consumer Quota - Quota limit",
      "conditionThreshold": {
        "filter": "resource.type = \"consumer_quota\" AND metric.type = \"serviceruntime.googleapis.com/quota/limit\"",
        "aggregations": [
          {
            "alignmentPeriod": "300s",
            "crossSeriesReducer": "REDUCE_NONE",
            "perSeriesAligner": "ALIGN_MEAN"
          }
        ],
        "comparison": "COMPARISON_GT",
        "duration": "0s",
        "trigger": {
          "count": 1
        }
      }
    }
  ],
  "alertStrategy": {},
  "combiner": "OR",
  "enabled": true,
  "notificationChannels": [],
  "severity": "SEVERITY_UNSPECIFIED"
}
```

**Comment by singhniraj08** [comment]
@saramirabi, Thank you reporting this issue. This looks like an [rate limit](https://ai.google.dev/gemini-api/docs/quota) error.
This repository is for issues related to website(https://ai.google.dev/) like documentation bugs or improvements. For issues related to Gemini, we would suggest you to use "Send Feedback" option in [Gemini docs](https://ai.google.dev/gemini-api/docs/api-key). Ref: Screenshot below. You can also post this issue on [Discourse forum](https://discuss.ai.google.dev/).

![image](https://github.com/google/generative-ai-docs/assets/110809167/7d11fa96-c1dc-45eb-bb7c-ec8d6609c383)

**Comment by SeaDude** [comment]
I faced the 429 error. Its quite misleading because to fix it, I had to connect a GCP Billing Account! As soon as I did that, the error went away. No where in any "quick start" documentation did I find this.
