### ISSUE TITLE
Missing notebook.

### ISSUE THREAD

**Issue by 0wwafa** [google/generative-ai-docs#440]
### Description of the bug:

In page: https://ai.google.dev/gemma/docs/gemma_chat
There is a link to github (this repository)
https://github.com/google/generative-ai-docs/blob/main/site/en/gemma/docs/gemma_chat.ipynb
and also a run in colab:
https://colab.research.google.com/github/google/generative-ai-docs/blob/main/site/en/gemma/docs/gemma_chat.ipynb

but the notebook is missing.

**Comment by anirudh161** [comment]
Fixed with PR - https://github.com/google/generative-ai-docs/pull/463
