### ISSUE TITLE
Gemini Refers To Itself As Bard

### ISSUE THREAD

**Issue by f4st4w4rd** [google/generative-ai-docs#441]
Gemini refers to itself as Bard or Chat GPT.

https://aistudio.google.com/app/prompts?state=%7B%22ids%22:%5B%221w5HoyeIvM8jxrFfWqqUqGnm0cU4i7iLh%22%5D,%22action%22:%22open%22,%22userId%22:%22100204558454174478902%22,%22resourceKeys%22:%7B%7D%7D&usp=sharing

![gemini-bard1](https://github.com/google/generative-ai-docs/assets/148639205/5447b595-dafd-473a-8d7b-8392a72f251f)

![gem-chatgpt](https://github.com/google/generative-ai-docs/assets/148639205/565c77bd-8691-4aec-998d-105d220fef80)

**Comment by singhniraj08** [comment]
@f4st4w4rd, Thank you reporting this issue. 
This repository is for issues related to website(https://ai.google.dev/) like documentation bugs or improvements. For issues related to Gemini API, we would suggest you to use "Send Feedback" option in [Gemini docs](https://ai.google.dev/gemini-api/docs/api-key). Ref: Screenshot below. You can also post this issue on [Discourse forum](https://discuss.ai.google.dev/).

![image](https://github.com/google/generative-ai-docs/assets/110809167/7d11fa96-c1dc-45eb-bb7c-ec8d6609c383)
