### ISSUE TITLE
Invalid operation: The `response.text` quick accessor requires the response to contain a valid `Part`, but none were returned. Please check the `candidate.safety_ratings` to determine if the response was blocked.

### ISSUE THREAD

**Issue by YiLuo59** [google/generative-ai-docs#461]
### Description of the bug:

My code is as following:

def model_generate(query, model):
    response = model.generate_content(query,
                                      generation_config=genai.types.GenerationConfig(
                                          max_output_tokens=3000,
                                      temperature=0.7),
                                      safety_settings={
        HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_NONE,
        HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_NONE,
        HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: HarmBlockThreshold.BLOCK_NONE,
        HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_NONE,
    })
    return response

response = model_generate(input, model)

Then I got error: Invalid operation: The `response.text` quick accessor requires the response to contain a valid `Part`, but none were returned. Please check the `candidate.safety_ratings` to determine if the response was blocked.

![image](https://github.com/google/generative-ai-docs/assets/77662961/d7867d24-a0ce-46a1-a988-7592df62e0ea)

How can I deal with that?

**Comment by singhniraj08** [comment]
@YiLuo59, Thank you reporting this issue. Similar issue is already filed in python SDK repo ([#python/373](https://github.com/google-gemini/generative-ai-python/issues/373))
This repository is for issues related to website(https://ai.google.dev/) like documentation bugs or improvements. Requesting you to close this issue, follow and +1 similar thread for updates. Thank you!

**Comment by architectyou** [comment]
@YiLuo59 

set the safety settings
https://ai.google.dev/gemini-api/docs/safety-settings?hl=en
