### ISSUE TITLE
Multi turn request with function calling return status 500

### ISSUE THREAD

**Issue by lairhas** [google/generative-ai-docs#469]
### Description of the bug:

I received status 500 when using REST API to do multi turn request.

### Any other information you'd like to share?

It happened when I define more than 2 tools.

**Comment by singhniraj08** [comment]
@lairhas,
Thank you reporting this issue. This looks like an intermittent error and should work now. 
This repository is for issues related to website(https://ai.google.dev/) like documentation bugs or improvements. For issues related to Gemini API, we would suggest you to use "Send Feedback" option in [Gemini docs](https://ai.google.dev/gemini-api/docs/api-key). Ref: Screenshot below. You can also post this issue on [Discourse forum](https://discuss.ai.google.dev/).

![image](https://github.com/google/generative-ai-docs/assets/110809167/7d11fa96-c1dc-45eb-bb7c-ec8d6609c383)
