### ISSUE TITLE
Only works locally

### ISSUE THREAD

**Issue by henriqueArrazao** [google/generative-ai-docs#473]
### Description of the bug:

Nothing much to share, locally works fine and in the server not. Server is in Germany. I checked and the API KEY is being sent.

This is the log
```
Server is running on port 3000 🚀
/app/node_modules/@google/generative-ai/dist/index.js:353
            throw new GoogleGenerativeAIFetchError(`Error fetching from ${url.toString()}: [${response.status} ${response.statusText}] ${message}`, response.status, response.statusText, errorDetails);
                  ^

GoogleGenerativeAIFetchError: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent: [403 Forbidden] 
    at _makeRequestInternal (/app/node_modules/@google/generative-ai/dist/index.js:353:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generateCon
```tent (/app/node_modules/@google/generative-ai/dist/index.js:752:22) {
  status: 403,
  statusText: 'Forbidden',
  errorDetails: undefined
}
```
Node.js v18.20.2

I tested the same Curl the lib requests in the Ubuntu terminal and it worked fine, so it's not a problem with the location.

After a lot of debugging got managed to get this new info:
<p>Your client does not have permission to get URL <code>/v1beta/models/gemini-1.5-flash:generateContent</code> from this server.  <ins>That’s all we know.</ins

**Comment by singhniraj08** [comment]
@henriqueArrazao 
Thank you reporting this issue. 
This repository is for issues related to website(https://ai.google.dev/) like documentation bugs or improvements. For issues related to Gemini API, we would suggest you to use "Send Feedback" option in [Gemini docs](https://ai.google.dev/gemini-api/docs/api-key). Ref: Screenshot below. You can also post this issue on [Discourse forum](https://discuss.ai.google.dev/).

![image](https://github.com/google/generative-ai-docs/assets/110809167/7d11fa96-c1dc-45eb-bb7c-ec8d6609c383)
