### ISSUE TITLE
Really 

### ISSUE THREAD

**Issue by Heyitsquoracom** [google/generative-ai-docs#483]
site/en/gemini-api/docs/semantic_retrieval.ipynb
[@iheyreally.com.json](https://github.com/user-attachments/files/16135137/%40iheyreally.com.json)
[stripe_backup_code.txt](https://github.com/user-attachments/files/16135138/stripe_backup_code.txt)
[Firefox-Browser-Developer-Logo-Assets.zip](https://github.com/user-attachments/files/16135139/Firefox-Browser-Developer-Logo-Assets.zip)
[chat_node_quickstart.ipynb 3.txt](https://github.com/user-attachments/files/16135140/chat_node_quickstart.ipynb.3.txt)

**Comment by singhniraj08** [comment]
@Heyitsquoracom,
We see that the issue [template](https://github.com/google/generative-ai-docs/issues/new/choose) has not been filled, could you please do so as it helps us analyze the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced. Thanks!
