### ISSUE TITLE
500 An internal error has occurred

### ISSUE THREAD

**Issue by Wiselnn570** [google/generative-ai-docs#489]
### Description of the bug:

Recently, I encountered this issue while using Gemini's API to input videos. It usually returns results normally for a while, but most of the time, it results in a 500 error code. I would like to know the specific solution; and whether a 500 error will consume the quota in the account. Thank you for your response.

**Comment by singhniraj08** [comment]
@Wiselnn570 ,
Thank you reporting this issue. This looks like an intermittent error and should work now. 
This repository is for issues related to website(https://ai.google.dev/) like documentation bugs or improvements. For issues related to Gemini API, we would suggest you to use "Send Feedback" option in [Gemini docs](https://ai.google.dev/gemini-api/docs/api-key). Ref: Screenshot below. You can also post this issue on [Google AI forum](https://discuss.ai.google.dev/).

![image](https://github.com/google/generative-ai-docs/assets/110809167/7d11fa96-c1dc-45eb-bb7c-ec8d6609c383)

**Comment by Wiselnn570** [comment]
OK, thanks
it works now

Niraj Singh ***@***.***> 于2024年7月22日周一 15:15写道：
