### ISSUE TITLE
InvalidArgument: 400 Image input modality is not enabled

### ISSUE THREAD

**Issue by hovanhoa** [google/generative-ai-docs#513]
### Description of the bug:

I ran this below code to make a prompt for an image
```
import google.generativeai as genai
import PIL.Image
import os

img = PIL.Image.open('<IMAGE_FILE>')

model = genai.GenerativeModel(model_name="<MY_TUNED_MODEL>")

response = model.generate_content([img])
print(response.text)
```

But It's return the exception: 

> google.api_core.exceptions.InvalidArgument: 400 Image input modality is not enabled for <MY_TUNED_MODEL>

I already researched for this exception but found nothing. can anyone help me?

### Any other information you'd like to share?
But It's worked if I try Gemini model (such as `gemini-1.5-flash`)

**Comment by luhhdaveyjr** [comment]
bug

**Comment by gmKeshari** [comment]
Hi @hovanhoa. Currently, model tuning is available for text and not for image & video.

**Comment by hovanhoa** [comment]
Hmm, thank you @gmKeshari

**Comment by zeroJor** [comment]
@gmKeshari will be available in the feature?, it's time hard to understand how Google AI Studio let's you create a data set using images, then you spend a lot of time feeding that data set and at the getting the response: "Currently, model tuning is available for text and not for image & video.".
