### ISSUE TITLE
Sample code for Android

### ISSUE THREAD

**Issue by YashjitPal** [google/generative-ai-docs#64]
Can I use the sample apps of PaLM API on Android?

**Comment by markmcd** [comment]
We have some sample apps up on the site for Android/Kotlin as well as Java, so you should be able to get something up and running. Checkout out the first few results from [this search](https://developers.generativeai.google/s/results?q=android%20quickstart), e.g. the [Text Quickstart for Android](https://developers.generativeai.google/tutorials/text_android_quickstart).

We should get the code for these into this repository... We can leave this open to track that.

**Comment by YashjitPal** [comment]
> We have some ~sample apps~ guides up on the site for Android/Kotlin as well as Java, so you should be able to get something up and running. Checkout out the first few results from [this search](https://developers.generativeai.google/s/results?q=android%20quickstart), e.g. the [Text Quickstart for Android](https://developers.generativeai.google/tutorials/text_android_quickstart).
> 
> We should get the code for these into this repository... We can leave this open to track that.

I'm not much in codes but i want to try the generative AI stuff. I tried the sge, bard and some others but here I saw more PaLM 2 LLM ai so I want to try these. I went to the page which you linked but unfortunately there were many codes. Can there be any app or website where I can paste the API key and can directly use it?

**Comment by williamito** [comment]
It sounds like you're looking for https://makersuite.google.com/ !

**Comment by williamito** [comment]
I'm sorry, I don't understand what you're hoping to do. In MakerSuite, you can use the Text prompt, Data prompt, and Chat prompt tools to try out the PaLM API without any coding, other than the prompt and examples. Check out the [quickstart guide](https://developers.generativeai.google/tutorials/makersuite_quickstart) for more info on how to use MakerSuite.

If you're referring to the **Get code** button, that could be used to take the prompt you created and add it to existing program code, but it doesn't sound like that's what you want to do.

If I'm misunderstanding something, can you provide an example of what "code" you don't know how to use?

**Comment by markmcd** [comment]
You can always come ask questions on [the discord server](https://developers.generativeai.google/guide/discord) too. There are plenty of experts there that can help you with basic coding questions or the PaLM API.

I don't think there's anything outstanding here so I'll close the issue. Let us know if you think there's still an issue or missing content.
