### ISSUE TITLE
Not able to communicate with the character

### ISSUE THREAD

**Issue by Talks2Bots** [google/generative-ai-docs#67]
I'm able to run the project and get the character to appear. However, the input field for texting with the character does not seem to be ready for input. Also, even though the microphone can be enabled and my voice appears to be heard, there's no indication that the ASR is working. Here is a video of what I am experiencing.  

https://github.com/google/generative-ai-docs/assets/37023314/3bc0d5db-77c1-489d-b3b8-13d3eedbb8d3

**Comment by Talks2Bots** [comment]
I see now that I need the API keys. It looks like I need to join the waitlist?

**Comment by MarkDaoust** [comment]
Yes, join the waitlist. It should be less than 48h.

**Comment by Talks2Bots** [comment]
Thanks!
