### ISSUE TITLE
Error when attempting to speak to character

### ISSUE THREAD

**Issue by Talks2Bots** [google/generative-ai-docs#73]
I now have the API keys installed in the project. I started up the character, activated the mic, and spoke. Nothing happened so I thought the speak recognition still wasn't working. But then I suddenly saw, for just a split second, the words that I had spoken appear in the box under "You." I had said "Hi pup, how are you doing" and that's what showed up in the box. But then, right after that, I got an error screen with this message."

Uncaught Runtime Error

Cannot read properties of undefined (reading 'concat')
Typeerror: Cannot read properties of undefined (reading 'concat')
at send Message (http://localhost:3000/static/js/bundle.js:316:34)

**Comment by eladkolet** [comment]
@MarkDaoust  Looks like this is what i get too - and this is because of staging-sandbox bison api access issue that can't be fixed https://github.com/google/generative-ai-docs/issues/74

**Comment by MarkDaoust** [comment]
Should be fixed by: https://github.com/google/generative-ai-docs/pull/87
