### ISSUE TITLE
Talking Character: Getting HTTP 403 for staging-sanbox bison API, but can't activate it from console - getting "Failed to load"

### ISSUE THREAD

**Issue by eladkolet** [google/generative-ai-docs#74]
Talking Character: Getting a 403 error that can't be fixed from console for the chat bison staging-sandbox API:
HTTP request: https://autopush-generativelanguage.sandbox.googleapis.com/v1beta1/models/chat-bison-001:generateMessage?key=<redacted>
HTTP response 403:
{
  "error": {
    "code": 403,
    "message": "Generative Language API (Staging) has not been used in project <redacted> before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/staging-generativelanguage.sandbox.googleapis.com/overview?project=<redacted> then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developers console API activation",
            "url": "https://console.developers.google.com/apis/api/staging-generativelanguage.sandbox.googleapis.com/overview?project=<redacted>"
          }
        ]
      },
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "SERVICE_DISABLED",
        "domain": "googleapis.com",
        "metadata": {
          "consumer": "projects/<redacted>",
          "service": "staging-generativelanguage.sandbox.googleapis.com"
        }
      }
    ]
  }
}

When visiting the suggested staging-sandbox URL - Getting the following console error:

Failed to load.
There was an error while loading [/apis/library/staging-generativelanguage.sandbox.googleapis.com?project=<redacted>](https://console.cloud.google.com/apis/library/staging-generativelanguage.sandbox.googleapis.com). Please try again.

It may be a browser or network issue. Go to the [loading issues help page ](https://cloud.google.com/cloud-console/docs/console-page-loading?_ga=2.266217414.-838602440.1686698301&_gac=1.114759029.1688493692.Cj0KCQjwho-lBhC_ARIsAMpgMofBan0wRX_R_bvdEEijkF07INHh0YBgPJ7-dK6MxhJIzALYDOHtYs0aAt9ZEALw_wcB) to troubleshoot the issue.

<img width="1148" alt="Screenshot 2023-07-04 at 3 32 48 PM" src="https://github.com/google/generative-ai-docs/assets/13738381/56a89614-6174-455b-9b5a-1786b0ed4fe9">

**Comment by markmcd** [comment]
Can you try updating the base URL in `constants.ts` to see if that helps? I'm not an owner of this project but those URLs won't be publicly accessible, so you can try the new base URL I've proposed in https://github.com/google/generative-ai-docs/pull/87. Let me know if that works.

**Comment by MarkDaoust** [comment]
Should be fixed by: https://github.com/google/generative-ai-docs/pull/87
