### ISSUE TITLE
travel-planner demo stuck at Day 1 itinerary

### ISSUE THREAD

**Issue by gangchen03** [google/generative-ai-docs#92]
Followed the [installation instruction](https://github.com/google/generative-ai-docs/tree/main/demos/palm/web/travel-planner#how-to-install) to run wanderlust demo locally:
```
yarn dev
```

Enter a destination (i.e I want to go to Galveston Beach Texas this weekend) or click one of the sample trip plan. The app shows the day 1 itinerary properly (without Map or place), then it stuck with `loading your itinerary...`, eventually page timed out and returns to the home page.

I do have proper API key set up for both Place and Generative language.

**Comment by gangchen03** [comment]
figured out the issue. 
I need to enable the Google Maps JavaScript API in order to run the demo.
Otherwise, the browser app will get the `Google Maps API error: Google Maps API error: ApiNotActivatedMapError`
I will submit a PR on documentation.

**Comment by keertk** [comment]
Hi @gangchen03 thanks for reporting this and identifying a fix! Appreciate it. Wondering if you had a chance to submit a PR?
