### ISSUE TITLE
Compiling problems

### ISSUE THREAD

**Issue by vincenzomallemace** [google/generative-ai-docs#98]
Hi everyone, 
big and amazing projects on this repo! thank you for sharing!!!

I'm reaching some problems with the npm start on my local workstation, here below the last attempt:

Compiled with problems:
×
ERROR in ./src/apis/mediapipe_audio_blendshapes.ts 19:0-92
Module not found: Error: Can't resolve './mediapipe/web/graph_runner/graph_runner' in 'C:\Users\VIMALLEM\OneDrive - Capgemini\Desktop\Codici APP\talking-character\src\apis'
ERROR in src/apis/mediapipe_audio_blendshapes.ts:17:59
TS2307: Cannot find module './mediapipe/web/graph_runner/graph_runner' or its corresponding type declarations.
    15 |  */
    16 |
  > 17 | import {createMediaPipeLib, GraphRunner, WasmModule} from './mediapipe/web/graph_runner/graph_runner';
       |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    18 |
    19 | declare interface AudioBlendshapesWasmModule {
    20 |   updateBlendshape: (name: string, value: number) => void;
ERROR in src/apis/mediapipe_audio_blendshapes.ts:44:10
TS2339: Property 'finishProcessing' does not exist on type 'MediaPipeAudioBlendshapes'.
    42 |    */
    43 |   getBlendshapes(): Blendshapes {
  > 44 |     this.finishProcessing();
       |          ^^^^^^^^^^^^^^^^
    45 |     return this.blendshapes;
    46 |   }
    47 | }
ERROR in src/apis/talkingHead.ts:17:58
TS2307: Cannot find module './mediapipe/web/graph_runner/graph_runner' or its corresponding type declarations.
    15 |  */
    16 |
  > 17 | import {createGraphRunner, GraphRunner, WasmModule} from './mediapipe/web/graph_runner/graph_runner';
       |                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    18 | import {createMediaPipeAudioBlendshapes, MediaPipeAudioBlendshapes} from './mediapipe_audio_blendshapes';
    19 | // import {trustedResourceUrl} from 'safevalues';
    20 |
ERROR in src/apis/talkingHead.ts:118:26
TS2339: Property 'wasmModule' does not exist on type 'MediaPipeAudioBlendshapes'.
    116 |         isV2?'talking_head_v2/talking_heads_v2_microphone_assets.js':'talking_head_v1/talking_heads_microphone_assets.js');
    117 |     wasmModule =
  > 118 |         audioBlendshapes.wasmModule as WasmModule & TalkingHeadsWasmModule;
        |                          ^^^^^^^^^^
    119 |     wasmModule.NUM_QUEUED_AUDIO_PACKETS = 0;
    120 |     audioBlendshapes.configureAudio(1, NUM_SAMPLES, SAMPLE_RATE);
    121 |     await audioBlendshapes.initializeGraph(isV2?'talking_head_v2/talking_heads_v2_demo.binarypb':'talking_head_v1/talking_heads_demo.binarypb');
ERROR in src/apis/talkingHead.ts:120:22
TS2339: Property 'configureAudio' does not exist on type 'MediaPipeAudioBlendshapes'.
    118 |         audioBlendshapes.wasmModule as WasmModule & TalkingHeadsWasmModule;
    119 |     wasmModule.NUM_QUEUED_AUDIO_PACKETS = 0;
  > 120 |     audioBlendshapes.configureAudio(1, NUM_SAMPLES, SAMPLE_RATE);
        |                      ^^^^^^^^^^^^^^
    121 |     await audioBlendshapes.initializeGraph(isV2?'talking_head_v2/talking_heads_v2_demo.binarypb':'talking_head_v1/talking_heads_demo.binarypb');
    122 |     // streamMicrophoneThroughGraph(audioBlendshapes);
    123 |   }
ERROR in src/apis/talkingHead.ts:121:28
TS2339: Property 'initializeGraph' does not exist on type 'MediaPipeAudioBlendshapes'.
    119 |     wasmModule.NUM_QUEUED_AUDIO_PACKETS = 0;
    120 |     audioBlendshapes.configureAudio(1, NUM_SAMPLES, SAMPLE_RATE);
  > 121 |     await audioBlendshapes.initializeGraph(isV2?'talking_head_v2/talking_heads_v2_demo.binarypb':'talking_head_v1/talking_heads_demo.binarypb');
        |                            ^^^^^^^^^^^^^^^
    122 |     // streamMicrophoneThroughGraph(audioBlendshapes);
    123 |   }
    124 | }
ERROR in src/apis/talkingHead.ts:148:22
TS2339: Property 'addAudioToStream' does not exist on type 'MediaPipeAudioBlendshapes'.
    146 |   const timestamp = lastAudioT + NUM_SAMPLES * 1000.0 / SAMPLE_RATE;
    147 |   if (timestamp > lastAudioT) {
  > 148 |     audioBlendshapes.addAudioToStream(audioData, 'input_audio', timestamp);
        |                      ^^^^^^^^^^^^^^^^
    149 |   }
    150 |   lastAudioT = timestamp;
    151 | }

can you help me?

**Comment by keertk** [comment]
Hi @vincenzomallemace I believe the issue you're facing is similar to the one reported here? https://github.com/google/generative-ai-docs/issues/62 
The issue and linked PR should be able to provide more info and a workaround.

I'm closing this one for now. Feel free to reopen if you face further issues!
